apiVersion: batch/v2alpha1
kind: ScheduledJob
metadata:
  name: scheduled-jobs-cleanup
spec:
  # every half of a hour
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          # 10 minutes timeout
          activeDeadlineSeconds: 600
          containers:
          - name: scheduled-jobs-cleanup
            image: willemvd/openshift-scheduledjobs-cleanup:1.0.1
          restartPolicy: OnFailure